# database properties
spring.datasource.url=jdbc:mariadb://localhost:3306/bipsync
spring.datasource.username=root
spring.datasource.password=comsc
spring.sql.init.mode=always
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
#debug=true
